#+Title: Introduction to Computing for Psychology Students
#+Author: Britt Anderson

* Overview
  This repository houses material I use in teaching at the University of Waterloo (Canada). Psychology undergraduates are usually Arts students who have limited quantitative and computing backgrounds. In order to assist them to use their computers as research tools I have organized a skills course to give them a brief background and exposure to several computing topics: 

  1. version control,
  2. operating system and software installation,
  3. using the terminal/command line,
  4. coding (Python and R),
     1. General purpose computing
     2. Data analysis
     3. Statistics
     4. Data Visualizations
  5. and the writing tools necessary for conducting
     1. a simple data collection (Psychopy),
     2. analysis, and
     3. generation of a reproducible report. 
	
  I have recorded a [[https://vimeo.com/448900968][brief video introduction]] to the course.

* Invitation

  While the material was developed for students at the University of Waterloo, I hope that some of the material may be useful to others. Feel free to provide feedback, or suggest material for inclusion.

* Organization of the Repository

  In the ~startHere~ directory I list an outline with a possible path through the material. That material is usually contained in a subdirectory of the ~topics~ folder. There may be further subdirectories if a topic has multiple levels or activities associated with it. The ~assessments~ directory contains versions of assignments I give the students to provide them a concrete opportunity to use the skills and in order to document their progress an to progress. If you are welcome to use the assignments to develop your own skills, but don't expect feedback or submit them to me. ~codeExamples~ contains examples submitted by past students, or written by me, to show how certain lessons might be tackled, or as educational illustrations. Many of the exercises are accompanied by videos or screencasts walking through various tasks. Those videos are hosted on [[https://vimeo.com/channels/i2c4p][Vimeo]] and in the *i2c4p* channel. Their titles will guide you to the accompanying activity. 

  The best way to use this repository is by forking or cloning your own version. There are internal links between files that don't work properly if you just open the code directory and click on one of the rendered versions of one of the ~.org~ files. Also, any exports to html that I include will open as raw files not as nicely rendered web pages, which they will often on your local computer. Links and file type associations should work better if you have work within a local clone of the repository than if you work by clicking on files in github or download files one at a time. Having your own version of all the files locally also makes it easier for you to copy and amend the material to suit your own needs. 

* Feel Free to Comment or Contribute
  If something is unclear go ahead and open an issue. If you find small changes like typos or broken links that you know how to fix please feel free to make a pull request, or if that is too inconvenient you can also point me to the needed fixes as an issue. 

  This material is taught in many ways and many places. If you have ideas about approaches you think may work better for me or want to talk about pedagogical strategies please feel free to email me. I am happy to entertain ideas for additional segments and topics, but all such suggestions or major restructuring of content will have to wait until this first version is completed and has been trialed by my Fall 2020 course at the [[https://uwaterloo.ca][University of Waterloo]].



