#+Title: For Loop with Python

* Task 
  Write a function that will print a list of characters unsorted, sorted, and combined. To complete this task you will need to be familiar with how to write a *for loop*, use python's *indexing*, and also how to use the [[https://realpython.com/python-formatted-output/][print format command]] [fn:1] 

* What it should look like
  I run your function with "trib". It prints t, r, i, b, then prints b, i, r, t, and then prints something like "The first letter of list one is 't', but it is 'b' in the sorted list... and so on through all the letters.

* Detailed Instructions
  1. Create a list of at least 8 individual characters.
  2. Make sure they are **not** in alphabetical order
  3. Print the letters one at a time.
  4. Print the letters sorted alphabetically one at a time, but /do not/ overwrite your original list.
  5. Print the letters from both lists with a format command that says which position the letter is in. 

* Comments
** Hints
   Remember not to re-invent the wheel. For example, does python have a function for sorting lists? Can you turn a "string" into a python list that would allow you to use indices? Lastly, note that a for loop can use more than one variable at a time. For my version I have a line that reads, 

   #+begin_src python :exports code :results never 
	 for i,l in enumerate(zip(myList,sorted(myList))):
   #+end_src

** How I Will Grade
   I will run your program from the command line e.g. =python firstLast2LstsSorted.py=. It will either spit out the correct lists or it won't. If it does you get full credit, and if not I will give partial credit and you can try to fix it for more points. 

* Footnotes

[fn:1] Not shown in lecture, but explained in many [[https://realpython.com/python-formatted-output/][places]]. Look for the =string.format()= method.
