#+Title: Installing RStudio on Windows and Macs

* Tasks
  1. Install RStudio
     1. This will require that you first install [[https://cran.r-project.org/][R]].
	The download links are on this page. One for each of the major operating systems. 
     2. Then you install the appropriate version of [[https://rstudio.com/products/rstudio/download/#download][RStudio Download Page]].
  2. Verify a successful installation by opening the program and getting it to tell you the answer to ~2+2~. You do this by typing exactly that equation and, depending on your defaults, hitting <Enter>.
  3. Demonstrate the above with appropriate screen shots submitted to the Learn Dropbox for [[https://learn.uwaterloo.ca/d2l/lms/dropbox/user/folder_submit_files.d2l?db=263433&grpid=0&isprv=0&bp=0&ou=802943][RStudio Installation.]]

* Comments
  We will be using linux based tools predominantly. However, it may take some users awhile to get linux installed and working. Therefore, we can begin our introduction to programming environments and markdown languages by using the RStudio tool installed on the users traditional software. The goal of this assessment is to make sure you can download the tool and get it up and running. *If* you already have Linux installed then do this activity with linux. *If not* return and repeat the exercise after you have successfully installed RStudio in Linux. 
