#+Title: Git Pull Request and Issues Assessment

* Task
  1. Generate a pull request for the [[https://github.com/brittAnderson/psych363Practice][psych363Practice]] repository on Github.
  2. Generate an issue for the psych363Practice repository. 

* Comment
  This course makes use of [[https://github.com][github]] for practicing how to use the version control program git. An important part of collaborating on code (or other material hosted on github, which might include text files) is to be able to give back or to alert the owner to a problem. This requires that you can both generate a *pull request* and that you can *open an issue.*

* Steps ([[https://vimeo.com/channels/i2c4p/456349516][video: steps illustrated]])  
  1. Previously you should have /forked/ the psych363Practice repository.
  2. Next you will need to clone your fork to your laptop.
  3. Check that you have your fork as a /remote./
  4. Add *my original* version of the repository as a second remote.
  5. To make sure you have the latest code, including all the other pulls generated by other students in the course you will want to:
     1. /Pull/ from *my original* repo.
     2. Accept and merge the changes if necessary.
     3. /Push/ these new changes to *your fork* on github.
     4. Verify the new changes made it there by looking at your fork in your browser. You may have to refresh your browser to see the changes.
     5. Now, in the =gitnames= subdirectory add a file with <yourfirstname>.txt. Put some simple sentence in it.
     6. *Add* this file.
     7. *Commit* this change.
     8. /Push/ to your fork.
     9. In your web browser initiate a *pull request.*
  6. When I receive your pull request I will accept it and give you half credit for this assignment (if you are a UWloo student).
  7. Next, open an /issue./ Just give it a simple title and make a simple statement. Our goal is to practice the process. Note the number of your issue and upload this number to the dropbox with your github name so I can match issues and pull requests to students. 

  Important Note: To help each other learn how to use git, github, and
  the material of this course, whether or not you are a UWaterloo
  student, use the [[https://github.com/brittAnderson/Intro2Computing4Psychology/issues][issue function in the Intro2Computing4Psychology]]
  repository to report your problems and confusions. That issue record
  will persist for future visitors to the repo who have the same
  question see how we dealt with it.
