#+Title: Report Generation with Org Babel

* Purpose
  Gain familiarity with report generation using org and babel and the inclusion of code blocks, graphics, and reference sections

* Task
  Provide an org file and its companion bib file that has a
  1. Title
  2. Author
  3. Sections for 
     - Introduction
     - Methods
     - Results
     - Conclusions
     - References
  4. Just have the editings and some minimal text. The purpose here is to get a working skeleton of a file that you can use and adapt later on.
  5. Cut and paste from your earlier examples of Rmd and Org files using R and Python to have some analysis in the results section. Make sure it includes as a minimum:
     - one code block
     - one figure
     - one inline code reference
     - one new citation other than the ones that were used in the example. 
       There are many ways to get references in the bibtex format. Scholar Google can export that format, and so will most of the major journal web pages.

* Comments
  I will evaluate submissions by compiling from org to pdf in my version of emacs. Either I will be able to produce a pdf of your report or I won't. If I can, and it meets all the requirements above then you will get full credit. 
