#+Title: Rmd to Html Assessment

* Task
Expand on your Rmd file submitted for Your First Rmd File to include additional material.

* Goal/Purpose
Markdown allows you to use plain text to give instructions to a /compiler/ to assemble a file with appropriate formatting. My assembling an html file with code and links from a markdown starter file you will see the basics of this approach.

1. A simple function definition (illustrations and examples will be provided in the lessons).

2. A code block using your function to produce output.

3. A for loop that counts from 1 to 10 and prints the even numbers.

Your submission should include both the Rmd file and the compiled html file produced in RStudio (see lessons for example of what these terms mean and what I am looking for).



* Instructions


1. Take your Rmd file from the first Rmd assessment as a starting point. 

2. Add a code block with a simple function definition.

3. Add another code block using your function to produce output.

4. Add a code block that executes a ~for~ loop that counts from 1 to 10 and prints the even numbers.

5. Submit both the Rmd file and the compiled html file produced in RStudio (you get the html by using the =knit to html= button in RStudio.
