# -*- org-link-file-path-type: relative; -*-
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Introduction
#+date: <2023-01-13 Fri>
#+author: Britt Anderson
#+email: britt@uwaterloo.ca
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.6-pre)
#+bibliography: /home/britt/gitRepos/Intro2Computing4Psychology/chapters/i2c4p.bib
#+cite_export: csl assets/chicago-note-bibliography-16th-edition.csl


* Welcome

These are the course notes for Psych363 at the University of Waterloo: An Introduction to Computing for Psychology students.

*Need more here. Just testing export for now*

This is the /index/ file for finding your way through the course topics and activities.

I recommend you follow the topics in the order below. Work through each chapter in sequence and make sure you understand the basics before moving on. This will remove much confusion.

The videos that you will find linked are not mean to replace the written material. They are intended to supplement it. If you start with the videos things will take longer and you will learn less. If you start with the assignments and then just try to skim around how to solve them you will learn much less, spend much more time on the activity, and get much more frustrated.

Read the chapter. Watch the Video. Try the Exercise.

** Goals
*stuff here*

We will be using Linux, but the installation process can be tricky and time consuming for some. Starting with RStudio allows me to introduce some of the ideas and concepts for programming while not letting us get stuck waiting for you to install a new operating system.

* Chapter RStudio
[[file:rstudio.org][RStudio]]

* Chapter Version Control
[[file:version-control.org][Version Control]]

* Linux

IAMHERE

* Linux Basics
** Installing Linux to Your Own Computer
   In this topic you will install a version of Linux on your own machine to use throughout this course (and after, I hope). 
*** Install Linux As A Virtual Machine 
    This is the new, preferred method. There are a number of videos for Mac and Windows users on how to do this. Note *importantly* the rules are different depending on whether you are using an M1 mac or an Intel mac. Don't know? Well find out. A good workman knows their tools.
    [[file:./topics/installUbuntu.org::*Steps in Detail - Virtual Machines][Start here]] for more detailed instructions.
*** Run from a USB (or SD card or external hard drive) *DEPRECATED*
    As I assume most new users will be hesitant to try and install a second operating system on their personal laptop they use for school and their personal work I am highlighting the use of Linux (Xubuntu) on a USB. You use the USB as your hard disk. You still use you computer's hardware (screen, keyboard, camera, etc), but the reading and writing of data takes place on the USB. It makes things slower, but you don't change your personal set up. Shut down. Remove USB. Start back up and you are back to where you are used to. It is a reasonable way to get started for experimenting and learning, but not an ideal way to run a system long-term. Consider converting to a more flexible and faster option in the future. Details of all the steps you have to take, and there are many, can be found in the [[file:./topics/installUbuntu.org][topics file]]. 
*** Install Xubuntu to a USB Topic
    [[file:./topics/installUbuntu.org][installUbuntu.org]]
    This ([[file:./topics/installingUbuntu_MacVersion.org][installingUbuntu_MacVersion.org]]) is an older file that may have some good hints still. It is here for historical reasons and for its links. As of Spring 2022 I think everything you need is in the regular installUbuntu.org file linked immediately above.
*** Dual Booting
    [[file:./topics/installUbuntu.org::*Dual Boot][Dual Boot]]
*** Linux Only
    [[file:./topics/installUbuntu.org::*Linux only][linux only]]
** Xubuntu Walkthrough
   [[https://vimeo.com/channels/i2c4p/453034310][Explaining your first Xubuntu Boot (video)]]
   [[https://vimeo.com/channels/i2c4p/453295883][First Boot Housekeeping Steps (video)]]
** Package Management
   [[https://vimeo.com/channels/i2c4p/453295879][Installing your first package (emacs) (video)]]
** Files
   1. [[file:./topics/installUbuntu.org][Installing Ubuntu Instructions]]
   2. [[file:../assessments/installXubuntuAssessment.org][Xubuntu Installation Assessment]]
** Videos
   1. [[https://vimeo.com/448906706][Intro to Booting Linux]]
   2. Virtual Machine Instructions from 2022
      1. [[https://vimeo.com/699876547][Your computer's bios]].
      2. Windows 11 [[https://vimeo.com/699876547][hypervisor]].
      3. [[https://vimeo.com/699876560][Install Ubuntu]].
      4. [[https://vimeo.com/699876529][Get the Virtual Box virtualization software.]]
      5. [[https://vimeo.com/699876529][Create the virtual machine]]
      6. [[https://vimeo.com/699876505][xubuntu iso.]]
      7. [[https://vimeo.com/699876505][Install xubuntu to your virutal machine]]machine.
      8. [[https://vimeo.com/699876351][Get the UTM software and use it to install a ubuntu iso]].
   3. Older files from Prior to 2022. May still have some useful examples. 
      1. [[https://vimeo.com/448908272][How To Get To Your Boot Menu]]
      2. [[https://vimeo.com/448908305][Booting Your Computer From a USB]]
      3. [[https://vimeo.com/448908514][A Persistent USB ISO]] 
      4. [[https://vimeo.com/448908150][Downloading the Rufus Tool]]
      5. [[https://vimeo.com/448908073][Getting the Xubuntu ISO]]
      6. [[https://vimeo.com/448908151][Installing Xubuntu to the USB]]
      7. [[https://vimeo.com/499572407][Intro to Trying this On a Mac]]
      8. [[https://vimeo.com/499617484][One method for the Mac]]
   4. [[https://vimeo.com/453034310][Explaining Your First USB Boot]]
   5. [[https://vimeo.com/453295883][What To Do After Your First Linux Boot]]
   6. [[https://vimeo.com/453295879][Installing Your First Package]]
*** Lower Resolution Screen Grabs (some redundancy to the above)
    1. [[https://vimeo.com/449006223][A Successful First Boot]]
    2. [[https://vimeo.com/453049176][USB Boot Version 2]]
    3. [[https://vimeo.com/453075287][Testing Persistence]]
    4. [[https://vimeo.com/453075670][First Shutdown]]
    5. [[https://vimeo.com/453049139][Sudo Apt Update]]
    6. [[https://vimeo.com/453075607][Sudo Apt Upgrade]]


