# -*- org-link-file-path-type: relative; -*-
#+Title: Outline
#+Author: Britt Anderson

* Overview
  This file contains a list of topics and associated activities for teaching yourself how to use your computer for research. Below you will find a list of topics with links to the relevant files in the other directories in this repository. The most convenient way to navigate the links may be to fork this repository and then clone it to your own computer and work from there. The ordering below is used in my course at the University of Waterloo, but you are encouraged to depart from that structure and navigate your own path as your needs and interests dictate. Most of the topics are reasonably self-contained, but of course, some of the later topics may require earlier skills or make reference to earlier activities. 

* Github
  We will be studying version control later when we have set up our Ubuntu installation and can use the terminal (aka: command line). To prepare for that we will create a [[https://github.com][Github account]] and gain some basic familiarity with the Github workflow. 
  1. [[https://vimeo.com/450563119][Intro to Github video]]
     =git= is a program that allows you to do version control. /Github/ is one of the larger social coding platform: an online agora for sharing, finding, and collaborating. It uses =git= as its base version control program, but it does other things too. Start to learn a bit about /Github/ here.
  2. [[https://vimeo.com/450563176][Github signup and walkthrough screencast video]]
     To participate at Github you have to be a member. It is free. Once you have done so, /fork/ this repository.
** Github Topic 
   [[file:~/gitRepos/introComp4Psych/topics/githubIDBasics.org][Github Topic File]]
* RStudio
** Rstudio on Windows and OSX
   This is a way to ([[https://vimeo.com/450563454][get started video)]] with some elements of programming without the need to install Linux, but it is more limited in its potential. Still, it may be a good starting point for some students to learn some of the tools and conventions before taking the plunge. 
   For this beginning effort we will:
   1. Download R ([[https://vimeo.com/450719112][downloadR video]])
   2. Download RStudio ([[https://vimeo.com/450719047][downloadRStudio video]])
   3. Verify they are working ([[https://vimeo.com/450719009][RStudio Walk-through video]])
   4. Generate a simple Rmd file to see some of the basic components of the markdown syntax ([[https://vimeo.com/450718879][simpleRmdDemo video]])
   5. Add some simple computing constructs including a 
      - variable
      - for loop
      - function
   6. Produce an Rmd file from the above
   7. And export it to an html file that we can open in a web browser and that displays correctly. 

   For the detailed instructions on the above steps consult [[file:~/gitRepos/introComp4Psych/topics/rStudioWinMacFirstSteps.org][the first steps Rstudio file in the topics directory.]]
*** Rstudio Win/Mac Topic File
    [[file:../topics/rStudioWinMacFirstSteps.org][rStudioWinMacFirstSteps.org]]
** Rstudio with Ubuntu
   Don't do this until you have a working installation of Ubuntu (or
   alternative linux) working on your computer. This topic is intended
   to start your R programming via a graphical inteface. After
   familiarizing yourself with the basic features of the R language
   and using a markdown dialect for mixing text and code we will
   explore other editors for this function. Later modules will focus
   in more detail on analysis and visualization.
* Linux Basics
** Installing Linux to Your Own Computer
   In this topic you will install a version of Linux on your own machine to use throughout this course (and after, I hope). 
*** Run from a USB (or SD card or external hard drive)
    As I assume most new users will be hesitant to try and install a second operating system on their personal laptop they use for school and their personal work I am highlighting the use of Linux (Xubuntu) on a USB. You use the USB as your hard disk. You still use you computer's hardware (screen, keyboard, camera, etc), but the reading and writing of data takes place on the USB. It makes things slower, but you don't change your personal set up. Shut down. Remove USB. Start back up and you are back to where you are used to. It is a reasonable way to get started for experimenting and learning, but not an ideal way to run a system long-term. Consider converting to a more flexible and faster option in the future. Details of all the steps you have to take, and there are many, can be found in the topics file. 
*** Install Xubuntu to a USB Topic
    [[file:../topics/installUbuntu.org][installUbuntu.org]]
*** Dual Booting
    [[file:~/gitRepos/introComp4Psych/topics/installUbuntu.org::*Dual Boot][Dual Boot]]
*** Linux Only
    [[file:~/gitRepos/introComp4Psych/topics/installUbuntu.org::*Linux only][linux only]]
** Xubuntu Walkthrough
** Package Management
* Version Control
** Git
*** Github
**** Github Basics
     [[*Github][Github ID and Forking Repositories]]
* Terminal (aka the Command Line)

* Emacs 

* Python

* R
** Getting R/Rstudio for Linux

* Data Handling

* Basic Plotting

* Programming Psychology Experiments

* Report Writing
  
** Org, markdown, and related dialects and tools

** LaTeX

** Reference Management

*** Biblatex (Bibtex)

** Mixing Code and Text

* Presentations
